### ISSUE TITLE
0.9.9 does not build on 10.9

### ISSUE THREAD

**Issue by ahankinson** [ruven/iipsrv#18]
The latest stable version (0.9.9) does not build on Mavericks 10.9.

The build fails with:

```
./Cache.h:52:10: fatal error: 'ext/pool_allocator.h' file not found
#include <ext/pool_allocator.h>
```

Fortunately this was fixed in f3beda8f2a5849c1f1ff102b14dc298bc2afaae7.

However, I was trying to contribute a formula for Homebrew for IIP when I ran into this problem. Homebrew likes to include only 'releases' in their system, using a tar file, instead of checking out the code from git.

Will there be an updated release that includes this fix sometime soon?

**Comment by ahankinson** [comment]
I think this can be closed now

**Comment by ruven** [comment]
A homebrew formula for iipsrv would still be good, however. Does anyone have something we could use for version 1.0?
